

/**
 * Class-File API (Preview Feature, JDK 22+).
 * <p>
 * This example uses the Class-File API to dynamically generate the bytecode
 * for a simple "HelloWorld" class and save it as a .class file.
 * <p>
 * The API provides a standard, supported way to parse, generate, and transform
 * Java class files without relying on third-party libraries like ASM.
 * <p>
 * To compile and run this generator (from the project root directory):
 * {@code javac --enable-preview --source 22 -d target/classes src/main/java/dev/fredpena/classfileapi/ClassFileApiExample.java}
 * <p>
 * To run the generator and create the HelloWorld.class file:
 * {@code java --enable-preview -cp target/classes dev.fredpena.classfileapi.ClassFileApiExample}
 */

void main() throws IOException {
    String className = "HelloWorld";
    Path classFilePath = Path.of(className + ".class");

    // Use the ClassFile API to build the bytecode for the class
    byte[] classBytes = ClassFile.of().build(ClassDesc.of(className),
            classBuilder -> {
                // 1. Define the class: public class HelloWorld extends Object
                classBuilder.withSuperclass(ConstantDescs.CD_Object)
                        .withFlags(ClassFile.ACC_PUBLIC);

                // 2. Define the constructor: public HelloWorld()
                classBuilder.withMethodBody(
                        "<init>", ConstantDescs.MTD_void, ClassFile.ACC_PUBLIC,
                        codeBuilder -> codeBuilder
                                .aload(0)
                                .invokespecial(ConstantDescs.CD_Object, "<init>", ConstantDescs.MTD_void)
                                .return_()
                );

                // 3. Define the main method: public static void main(String[] args)
                classBuilder.withMethodBody(
                        "main", MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_String.arrayType()),
                        ClassFile.ACC_PUBLIC | ClassFile.ACC_STATIC,
                        codeBuilder -> {
                            // GetIO, load a string, and call println
                            ClassDesc systemClass = ClassDesc.of("java.lang.System");
                            ClassDesc printStreamClass = ClassDesc.of("java.io.PrintStream");
                            MethodTypeDesc printlnMethod = MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_String);

                            codeBuilder.getstatic(systemClass, "out", printStreamClass);
                            codeBuilder.ldc("Hello from a generated class!");
                            codeBuilder.invokevirtual(printStreamClass, "println", printlnMethod);
                            codeBuilder.return_();
                        }
                );
            });

    // Write the generated bytes to a .class file
    Files.write(classFilePath, classBytes);

    IO.println("Successfully generated " + classFilePath.toAbsolutePath());
}
